### ISSUE TITLE
Collab example

### ISSUE THREAD

**Issue by msaroufim** [kelvin-jose/bert-sentiment#1]
Hi Kelvin, I really enjoyed your blog post and used it to build an example working in Google Collab. If you enjoyed it feel free to use in the README. I think it would generally be useful to have a README also linking to your great blog post https://medium.com/swlh/serving-a-torch-model-using-fastapi-37a56220ea3f

I think there's still a minor issue with this line and I'll have some more time to look into it later today

```
return torch.sigmoid(output[0]).cpu().detach().numpy()
```

https://drive.google.com/file/d/15XUuIYt-hU3-cHQSKNHjzWT-G836Fg9D/view?usp=sharing

**Comment by kelvin-jose** [comment]
hi @msaroufim I will look into the issue and resolve it asap.
